### ISSUE TITLE
Tasks never call destructor for emplaced data

### ISSUE THREAD

**Issue by LuisAntonRebollo** [GameTechDev/GTS-GamesTaskScheduler#3]
Hi :)

Thank you for sharing this library.

Maybe I'm missing something, but it looks like emplaced data for tasks never get their destructors called. This causes memory leaks or, even worse issues if destructors are used for important logic. As the code calls constructors for the data, I was assuming the same will happen with destructors. 

If it's designed to avoid handling destructors, maybe addition of a static assert with std::is_trivially_destructible would help to avoid issues.

If it is a bug or missing code, I think it should be possible to store the data with an additional pointer to a destructor function to resolve the ambiguity of the type, or add a new interface to explicitly call the destructor and an assert to guard when this call is missing for types with non trivial destructors. 

After some quick changes in my code, both approach are working fine here.

**Comment by bretalfieri** [comment]
Yes, the lack of destructor call is intentional. I have a section about this in the tutorials. The rational for no destructors came from measuring overhead. I tried both type erased destructors and polymorph tasks, and both added a fair amount of overhead. I'll add the suggested assert to reduce confusion. Also, if you have other solutions to enable destructors, please submit a pull request! Thanks for trying out GTS!

**Comment by LuisAntonRebollo** [comment]
I created a PR with another idea on how to approach the issue. #4 

> The main idea is to inline the task execution code in a wrapper together with the code for destruction, in this way we dont need to add any additional indirect function call.

**Comment by LuisAntonRebollo** [comment]
I created another PR with the "debug only" idea i poster before. #5

> This code only works when GTS_ASSERT are enabled, in this way the performance in release in not affected. The new asserts ensure Task::destructData will be called before any other data initialization or Task destruction.

**Comment by bretalfieri** [comment]
Thanks for the PR idea with the nested lambda! I'll play around with this and see if I can avoid the C++20 requirement (I'm trying to keep the compiler min-spec VS2015), well as having to pull code in from the scheduling algorithm hot-path. I'll also re-time the type erased destructors to see if my previous result still hold true. It's been ~1 year since I looked at that.

**Comment by bretalfieri** [comment]
Good new! The type erasure version of task destruction appears to have far less impact that I remember. I ran some perf tests and inspected them in vtune. Running times showed no impact and vtune showed minimal impact to MicroScheduler::_freeTask. Given that, I'll put the type erasure version back in. Thanks for making me look at this again!

**Comment by LuisAntonRebollo** [comment]
Thx a lot for your time :)

Looking forward to start using GTS at work and in my personal projects.

**Comment by bretalfieri** [comment]
Fixed!
